 let a = 1;
 let b=2;
 console.log("a");
 console.log("a");
 console.log("a+b");

 try{
    console.log(a+c);
 }
 catch(err){
    console.log("err");
 }
 
 console.log("a");
 console.log("a");